Upgrade dependencies and move away from unmaintained crates
etke/checksec.rs pull request #20
Opened 2022-09-30 06:58 UTC by marcograss

this PR upgrades the dependencies, the only one involving some changes in the code is Clap to the next major 
It also replaces memmap with memmap2 since the original crate is unmaintained

I only tested on macOS so it's better to give it a try on Windows since the windows crate has been updated as well

2022-10-08 23:02 UTC, etke commented
Thanks for the updates, mind rebasing your branch on current master?

2022-10-09 13:32 UTC, marcograss commented
> Thanks for the updates, mind rebasing your branch on current master?

done, is the CI running?

2022-10-10 13:46 UTC, cgzones commented on src/main.rs
> +    let format = if args.get_flag("json") {
`-j `-p` would not work now

2022-10-10 13:46 UTC, cgzones commented on src/main.rs
> +                .help("Include process memory maps (linux only)")
why drop `.requires("pid")`?

2022-10-10 16:04 UTC, marcograss commented
nice catches, I fixed them in the new commit. I got confused while rebasing

2022-10-11 19:14 UTC, etke commented
Appears the latest windows crate added `Option` around some of the used API args https://github.com/etke/checksec.rs/actions/runs/3220737878/jobs/5285290254

If you want to update to fix those you can or you can drop the windows crate update from this PR, and I'll update the crate and associated code in a subsequent commit.

2022-10-13 12:21 UTC, marcograss commented
I fixed the build on windows

2022-10-13 16:49 UTC, etke requested changes
Thank you for addressing feedback received so far, a few small formatting changes then PR is good to merge.

2022-10-13 16:49 UTC, etke commented on Cargo.toml
> -codegen-units = 1   # Reduce number of codegen units to increase optimizations
Would prefer to keep comments in an aligned column for readability.

2022-10-13 16:49 UTC, etke commented on src/main.rs
> -        .arg(
Args were reordered in previous commit from @cgzones, would prefer to keep alphabetical order.

2022-10-13 16:49 UTC, etke commented on src/main.rs
> +        .arg(Arg::new("pid").long("pid").value_name("PID").help(
Please align to existing arg formatting with `.long`, `.value_name` and `.help` on separate lines.

2022-10-13 17:42 UTC, marcograss commented
I addressed the code formatting errors, however the one involving the Arg subcalls (help, long_name etc) might be a little fragile if cargo fmt behavior changes in the future, anyway for now it's ok

2022-10-13 17:59 UTC, etke approved these changes

2022-10-13 18:00 UTC, merged

2022-10-13 18:00 UTC, etke commented
Merged. Thanks for your contributions!